image: golang:1.8.1

variables:
  REPO_NAME: github.com/dimitertodorov/gomi

before_script:
  - go version
  - echo $CI_BUILD_REF
  - echo $CI_PROJECT_DIR
  - make promu

stages:
  - test

test-project:
  stage: test
  script:
    - mkdir -p $GOPATH/src/$REPO_NAME
    - mv $CI_PROJECT_DIR/* $GOPATH/src/$REPO_NAME
    - cd $GOPATH/src/$REPO_NAME
    - go get -u github.com/kardianos/govendor
    - govendor test +local  -v

release-job:
  stage: build
  script:
    - mkdir -p .build/linux-amd64
    - mkdir -p .build/windows-amd64
    - mkdir -p ./.release/
    - env PREFIX=.build/linux-amd64 GOOS=linux GOARCH=amd64 make build
    - env PREFIX=.build/windows-amd64 GOOS=windows GOARCH=amd64 make build
    - env GOOS=linux GOARCH=amd64 promu tarball --prefix ./release .build/linux-amd64
    - env GOOS=windows GOARCH=amd64 promu tarball --prefix ./release .build/windows-amd64
  artifacts:
    paths:
    - .release/*.tar.gz
  only:
    - tags