# GitLab CI Build/Test

stages:
  - build
  - test

build-my-project:
  stage: build
  script:
    - cd $CURRENT_BUILD_PATH
    - promu build

test-my-project:
  stage: test
  script:
    - cd $CURRENT_BUILD_PATH
    - go test ./omi