# GitLab CI Build/Test

stages:
  - test

test-gomi:
  stage: test
  script:
    - rm -rf /home/gitlab-runner/golang/src/github.com/dimitertodorov/gomi
    - rsync -av --exclude='.git/' ../gomi /home/gitlab-runner/golang/src/github.com/dimitertodorov
    - cd /home/gitlab-runner/golang/src/github.com/dimitertodorov/gomi
    - go test -v ./omi