# GitLab CI Build/Test

stages:
  - test

test-gomi:
  stage: test
  script:
    - cp -r ../gomi /home/gitlab-runner/golang/src/github.com/dimitertodorov/gomi
    - cd /home/gitlab-runner/golang/src/github.com/dimitertodorov/gomi
    - go test -v ./omi