image: golang:1.8.1

variables:
  REPO_NAME: github.com/dimitertodorov/gomi

before_script:
  - go version
  - echo $CI_BUILD_REF
  - echo $CI_PROJECT_DIR
  - make promu
  - mkdir -p $GOPATH/src/$REPO_NAME
  - setopt -s glob_dots
  - mv $CI_PROJECT_DIR/* $GOPATH/src/$REPO_NAME
  - cd $GOPATH/src/$REPO_NAME

stages:
  - test
  - build

test-project:
  stage: test
  script:
    - go get -u github.com/kardianos/govendor
    - govendor test +local  -v
  except:
    - tags

release-job:
  stage: build
  script:
    - mkdir -p .build/linux-amd64
    - mkdir -p .build/windows-amd64
    - mkdir -p ./.release/
    - cat .promu.yml
    - env GOOS=linux GOARCH=amd64 promu build --prefix .build/linux-amd64
    - env GOOS=windows GOARCH=amd64 promu build --prefix .build/windows-amd64
    - env GOOS=linux GOARCH=amd64 promu tarball --prefix ./.release/ .build/linux-amd64
    - env GOOS=windows GOARCH=amd64 promu tarball --prefix ./.release/ .build/windows-amd64
  artifacts:
    paths:
    - .release/*.tar.gz
  only:
    - tags