image: golang:1.8.1

variables:
  REPO_NAME: github.com/dimitertodorov/gomi

before_script:
  - go version
  - echo $CI_BUILD_REF
  - echo $CI_PROJECT_DIR
  - make promu

stages:
  - test

test-project:
  stage: test
  script:
    - mkdir -p $GOPATH/src/$REPO_NAME
    - mv $CI_PROJECT_DIR/* $GOPATH/src/$REPO_NAME
    - cd $GOPATH/src/$REPO_NAME
    - go get -u github.com/kardianos/govendor
    - govendor test +local  -v